name: Build the application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest  

    env:
      Solution_Name: xmlmethodchanger/XmlMethodChanger.sln
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: |
        dotnet add $env:Solution_Name package CommandLineParser --version 2.8.0
        dotnet restore $env:Solution_Name
      
    - name: Build
      run: dotnet build $env:Solution_Name --configuration Release --no-restore
      
    # See what we built?
    - name: look around
      shell: bash
      run: |
       ls -lh .
       ls -lh ..
       ls -lh xmlmethodchanger/XmlMethodChanger.cmd
       ls -lh xmlmethodchanger/XmlMethodChanger.lib
       ls -lh ../XmlMethoChanger/
